[mypy]
# check_untyped_defs = True
# disallow_untyped_defs = True -- not yet feasible

# strict = True -- only try to enable once everything is typed
strict_equality = True

[mypy-ansible.*]
# ansible-core has partial typing information
follow_untyped_imports = True
